### ISSUE TITLE
Issue upgrading from IntelOwl 4.2.2 to 4.2.3

### ISSUE THREAD

**Issue by nebu10uz** [intelowlproject/IntelOwl#1620]
## What happened

Issue upgrading from IntelOwl 4.2.2 to 4.2.3. Once upgraded as described in IntelOwl official document, the intelowl_celery_worker_default started to report:

`PermissionError: [Errno 13] Permission denied: '/var/log/intel_owl/django/authentication.log`

I let the containers run for a few minutes then I stop them and restarted as described in the IntelOwl official document, however, the error continued.

I later solved this by using the following command to remove the DB:

`sudo python3 start.py prod down -v`

Once the upgraded version (4.2.3) was running I proceeded to create the superuser for access since I lost it by removing the DB:

`docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser` 

However, once I logged on with newly created credentials, I received several errors such as "Cannot fetch user info" and "500 internal server error" and this stalled the IntelOwl application. I then restarted intelOwl but I continued to receive the same errors. I since then went back to my previous snapshot and I'm currently using version 4.2.2.
 

## Environment
1. OS: Ubuntu 22.04.2 LTS - KVM
2. IntelOwl version: 4.2.3

##  What did you expect to happen
Successful upgrade from 4.2.2 to 4.2.3 with access to the portal and all my original configurations preserved and operating as normal.

## How to reproduce your issue
Create and run a KVM Ubuntu 22.04.2 LTS and install IntelOwl 4.2.2. Then upgrade to 4.2.3 as described in the official documentations.

## Error messages and logs
`PermissionError: [Errno 13] Permission denied: '/var/log/intel_owl/django/authentication.log`
`Cannot fetch user info`
`500 internal server error`

**Comment by mlodic** [comment]
Hello, thanks for reporting.

The error you mentioned is really making me sick because not always happens and it is due to concurrency problems between django and celery. With the new version we added new log files. If you have an already working IntelOwl instance (like you), it may happen that those files are not correctly ch-owned by the user `www-data` which runs the application containers.

The simple solution would have been to just:
`sudo chown www-data:www-data /var/lib/docker/volumes/intel_owl_generic_logs/_data/django` and then restart the application.
I'll add some notes in the release/changelog/doc for other people.

Then, about the `superuser` error, it should not happen if you have correctly deleted all the volumes and starting from scratch. I would need to get the additional logs generated in `/var/lib/docker/volumes/intel_owl_generic_logs/_data/` to debug further and understand the problem otherwise I cannot replicate the issue.

**Comment by mlodic** [comment]
added explanation here: 55da642b97612592d0db436f52d9671c2ddb0917

**Comment by nebu10uz** [comment]
Hi @mlodic,

The chown for user www-data worked and the latest version 4.2.3 is up and running. 

However, when I logon to the IntelOwl portal with my saved user, I get the following error: (`/var/ib/docker/volumes/intel_owl_generic_logs/_data/django/django_errors.log`):

```
RuntimeError: generator raised StopIteration
2023-03-31 14:39:37,049 - django.request - log_response - ERROR - Internal Server Error: /api/me/access
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 118, in __iter__
    obj = model_cls.from_db(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 576, in from_db
    values = [
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 577, in <listcomp>
    next(values_iter) if f.attname in field_names else DEFERRED
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/certego_saas/ext/middlewares.py", line 36, in __call__
    f"request {request.method} {request.path} received from {request.user}"
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
RuntimeError: generator raised StopIteration
2023-03-31 14:39:37,792 - django.request - log_response - ERROR - Internal Server Error: /api/get_playbook_configs
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 118, in __iter__
    obj = model_cls.from_db(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 576, in from_db
    values = [
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 577, in <listcomp>
    next(values_iter) if f.attname in field_names else DEFERRED
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/certego_saas/ext/middlewares.py", line 36, in __call__
    f"request {request.method} {request.path} received from {request.user}"
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/backends.py", line 162, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
```

And here's me user:hunter trying to access the plugin configs from the portal (`/var/ib/docker/volumes/intel_owl_generic_logs/_data/django/api_app.log`):

```
2023-03-31 14:39:36,776 - api_app.core.views - get - ERROR - get_plugin_configs requester:hunter error:t
oo many values to unpack (expected 3).
Traceback (most recent call last):
  File "/opt/deploy/intel_owl/./api_app/core/views.py", line 128, in get
    ac = self.serializer_class.read_and_verify_config(request.user)
  File "/usr/local/lib/python3.9/site-packages/cache_memoize/__init__.py", line 131, in inner
    result = cache.get(cache_key, MARKER)
  File "/usr/local/lib/python3.9/site-packages/django/core/cache/backends/db.py", line 52, in get
    return self.get_many([key], version).get(key, default)
  File "/usr/local/lib/python3.9/site-packages/django/core/cache/backends/db.py", line 88, in get_many
    for key, value, expires in rows:
ValueError: too many values to unpack (expected 3)
```

From (`/var/ib/docker/volumes/intel_owl_generic_logs/_data/django/api_app_errors.log`):

```
2023-03-31 14:57:12,304 - api_app.core.views - get - ERROR - get_plugin_configs requester:hunter error:g
enerator raised StopIteration.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 189
, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/mixins.py", line 15, in get_cache
d_value
    return instance._state.fields_cache[cache_name]
KeyError: 'organization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 118, in __iter__
    obj = model_cls.from_db(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 576, in from_db
    values = [
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 577, in <listcomp>
    next(values_iter) if f.attname in field_names else DEFERRED
StopIteration
```


Looks like it has to do with the SessionStore. Let me know if you'll need for info from the logs.

Thanks!

**Comment by mlodic** [comment]
I am happy to hear the first problem was solved.

Then, thank you for sharing the logs. The problem is that is something related to internal management of the cache in the database. This is another non-easy to replicate bug and I don't have any idea what is messing with your cache, honestly.

The noob suggestion that I would tell you is: reinstall everything from stratch if possible because we don't have any evidence that this would happen again in that case and we've never seen this error in our production environments.

Then, we are working for a new major version of IntelOwl (like we do every year) and we are removing that caching mechanism anyway so it is not worth to us to investigate this further

**Comment by nebu10uz** [comment]
> 

No problem. I'll reinstalled from scratch then.

Thanks for all the help. Much appreciated!

**Comment by nebu10uz** [comment]
Do you have any tips on how to remove all the IntelOwl containers so that I can install  from scratch?

**Comment by nebu10uz** [comment]
Ok, so I did everything from scratch. I installed a new Ubuntu 22.04 as previously and installed the latest version of intelOwl v.4.2.3 and no dice. I'm getting the same cache error or the "Cannot fetch user access information" upon logon.

I'm going to wait it out until a new version comes out because this one doesn't like me.

**Comment by nebu10uz** [comment]
I found this but I'm not sure if it's relevant to my issue:

`# To fix this you need to remove sessions from cache, e.g.

from django.contrib.sessions.models import Session
Session.objects.all().delete()`

Reference: https://stackoverflow.com/questions/54722170/django-sessionstore-object-has-no-attribute-session-cache#60255596
