### ISSUE TITLE
[Error] settings.DRF_RECAPTCHA_SECRET_KEY must be set.

### ISSUE THREAD

**Issue by pypygeek** [intelowlproject/IntelOwl#1665]
## Environment
1. OS: ubuntu 20.04.6 LTS (5.4.0-147)
2. IntelOwl version: 4.2.3
3. docker version: 20.10.21
4. docker-compose version: 2.11.2
5. python version:  3.8.10

##  What did you expect to happen
Execute that command without issue and log no errors
`docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser`

## How to reproduce your issue
`
git clone https://github.com/intelowlproject/IntelOwl
cd IntelOwl/
cd docker/
cp env_file_app_template env_file_app
cp env_file_postgres_template env_file_postgres
cp env_file_integrations_template env_file_integrations
vi env_file_app

env_file_app
DJANGO_SECRET=GENERATOR_DJANGO_SECRET(https://miniwebtool.com/django-secret-key-generator/)

cd ..
./initialize.sh
python3 start.py prod up
docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser
![error](https://user-images.githubusercontent.com/19469996/233951300-a4d66043-8868-4f55-8c16-dcffe195e14e.png)

`

## Error messages and logs
`
Traceback (most recent call last):
  File "/opt/deploy/intel_owl/manage.py", line 25, in <module>
    main()
  File "/opt/deploy/intel_owl/manage.py", line 21, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/drf_recaptcha/checks.py", line 18, in recaptcha_system_check
    raise ImproperlyConfigured("settings.DRF_RECAPTCHA_SECRET_KEY must be set.")
django.core.exceptions.ImproperlyConfigured: settings.DRF_RECAPTCHA_SECRET_KEY must be set.
`

**Comment by pypygeek** [comment]
env_file_app edit
# drf-recaptcha
## localhost, internal deployments
RECAPTCHA_SECRET_KEY_IO_LOCAL="testkey"
## public deployment
RECAPTCHA_SECRET_KEY_IO_PUBLIC="testkey"
