### ISSUE TITLE
Bug on create API documentation through spectacular

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#1742]
Using `docker exec -it intelowl_uwsgi python manage.py spectacular --file docs/source/schema.yml && make html`
the following stacktrace is generated
```
Traceback (most recent call last):
  File "/opt/deploy/intel_owl/manage.py", line 25, in <module>
    main()
  File "/opt/deploy/intel_owl/manage.py", line 21, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/management/commands/spectacular.py", line 72, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/generators.py", line 233, in parse
    assert isinstance(view.schema, AutoSchema), (
AssertionError: Incompatible AutoSchema used on View <class 'api_app.analyzers_manager.views.AnalyzerConfigViewSet'>. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?
```

**Comment by mlodic** [comment]
DRF spectacular will be dismissed. See #2043
