### ISSUE TITLE
[Django admin] AnalyzerConfig create new PluginConfigs instead of editing the present ones

### ISSUE THREAD

**Issue by federicofantini** [intelowlproject/IntelOwl#1808]
## What happened
I created a new AnalyzerConfig ("save as new") in the Django Admin page, after editing fields I get an integrity error because there are two PluginConfig instead of the one edited.

## Environment
1. OS: Ubuntu 22.04.2 LTS
2. IntelOwl version: 5.0.1

##  What did you expect to happen
AnalyzerConfig should edit the PluginConfigs instead of creating another one.

## How to reproduce your issue
- copy as new an AnalyzerConfig such as CapeSandbox
- edit a field
- reload the page

## Error messages and logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1894, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1751, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1849, in _changeform_view
    media = media + inline_formset.media
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/helpers.py", line 457, in media
    media = self.opts.media + self.formset.media
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 518, in media
    if self.forms:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 205, in forms
    return [
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 206, in <listcomp>
    self._construct_form(i, **self.get_form_kwargs(i))
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 1117, in _construct_form
    form = super()._construct_form(i, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 737, in _construct_form
    form = super()._construct_form(i, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 244, in _construct_form
    form = self.form(**defaults)
  File "/opt/deploy/intel_owl/api_app/core/forms.py", line 40, in __init__
    pc = PluginConfig.objects.get(parameter=instance, owner__isnull=True)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /admin/analyzers_manager/analyzerconfig/CapeSandboxTest/change/
Exception Value: get() returned more than one PluginConfig -- it returned 2!
```

**Comment by 0ssigeno** [comment]
Fixed on commit db80d8f33696c290fd99fac11a1b32b510017d1f
