### ISSUE TITLE
script to migrate users for v4

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#934]
We need to add an helper script to allow IntelOwl users to migrate their database to the new IntelOwl v4 version (see **https://github.com/intelowlproject/IntelOwl/pull/856** where we started to use the `certego_saas` package)

**Comment by mlodic** [comment]
`intelowl_uwsgi           | Traceback (most recent call last):
intelowl_uwsgi           |   File "/opt/deploy/intel_owl/manage.py", line 25, in <module>
intelowl_uwsgi           |     main()
intelowl_uwsgi           |   File "/opt/deploy/intel_owl/manage.py", line 21, in main
intelowl_uwsgi           |     execute_from_command_line(sys.argv)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
intelowl_uwsgi           |     utility.execute()
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
intelowl_uwsgi           |     self.fetch_command(subcommand).run_from_argv(self.argv)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
intelowl_uwsgi           |     self.execute(*args, **cmd_options)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
intelowl_uwsgi           |     output = self.handle(*args, **options)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
intelowl_uwsgi           |     res = handle_func(*args, **kwargs)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 95, in handle
intelowl_uwsgi           |     executor.loader.check_consistent_history(connection)
intelowl_uwsgi           |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
intelowl_uwsgi           |     raise InconsistentMigrationHistory(
intelowl_uwsgi           | django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency certego_saas.0001_initial on database 'default'.`
